[project]
name = "clarity-shield"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/ClarityShield/clarity-shield/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.shield]
path = "contracts/shield.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
